version: '3'
dotenv: ['.env']

env:
  WSL_PATH_FOLDER_SOCLE_ROOT: "{{WSL_PATH_FOLDER_SOCLE_ROOT}}"
  WSL_PATH_FOLDER_PROJECTS_ROOT: "{{WSL_PATH_FOLDER_PROJECTS_ROOT}}"
  PROJECT_ROOT_FOLDER_IN_DOCKER: "{{PROJECT_ROOT_FOLDER_IN_DOCKER}}"
  CLIENT: "{{CLIENT}}"
  PROJECT: "{{PROJECT}}"
  PROJECT_NAME: "{{PROJECT_NAME}}"

vars:
  DOCKER_GID:
    sh: 'getent group docker | cut -d: -f3'
  DOCKER_ADMIN_COMP: docker --log-level=ERROR compose -f launcher-docker-compose.yml --project-name {{PROJECT_NAME}} --profile runner-dev
  ENV_IP_WSL_ETH:
    sh: printenv IP_WSL_ETH


tasks:

  service-running:
    desc: "📋 Available services:"
    silent: true
    cmds:
      - '{{.DOCKER_ADMIN_COMP}} ps --services'

  security:
    desc: "🔒 Run Trivy security scan"
    silent: true
    internal: true
    cmds:
      - echo "🔒 Running Trivy security scan..."
      - 'docker run --rm -v $(pwd):/app -v ${HOME}/.trivy/.cache:/root/.cache/ -w /app aquasec/trivy:latest --exit-code 1 fs --scanners vuln .'

  bash:
    desc: "🐚 Start a bash shell in webserver for new project"
    silent: true
    vars:
      SERVICE_NAME:
        sh: '{{if .SERVICE_NAME}}echo {{.SERVICE_NAME}}{{else}}task service-running | gum choose{{end}}'
    cmds:
      - echo "🔍 Running Bash access..."
      - '{{.DOCKER_ADMIN_COMP}} exec -e XDEBUG_MODE=off {{.SERVICE_NAME}} bash'


  default:
    desc: "Show help message"
    silent: true
    cmds:
      - task --list

  start:
    desc: "🚀 Start webserver for new project development"
    silent: true
    deps:
      - traefik_up
      - stop
    cmds:
      - echo "🚀 Start webserver for new project development"
      - '{{.DOCKER_ADMIN_COMP}} --project-name {{.PROJECT_NAME}} up -d'

  stop:
    desc: "⏹️ Stop the docker-compose stack for new project"
    silent: true
    cmds:
      - echo "⏹️ Stop the docker-compose stack for new project"
      - '{{.DOCKER_ADMIN_COMP}} --profile runner-dev down --remove-orphans'

  check_permissions:
    desc: "Ensure bin/healthcheckTraefik.sh is executable"
    silent: true
    internal: true
    cmds:
      - 'if [ ! -x bin/healthcheckTraefik.sh ]; then sudo chmod +x bin/healthcheckTraefik.sh; fi'

  traefik_up:
    desc: "🌐 Start and check Traefik health"
    internal: true
    silent: true
    deps:
      - check_permissions
    cmds:
      - ./bin/healthcheckTraefik.sh

